/* Generated by gen-stubs.c from signature file empty_stubs */

#include "jam.h"
#include "jni-stubs.h"

extern void *jni_env;

/* Static signatures */

/* Non-static signatures */


JNIStub jni_static_stubs[] = {
    {NULL, NULL}
};

JNIStub jni_stubs[] = {
    {NULL, NULL}
};
