/* Generated by gen-stubs.c from signature file empty_stubs */

#include "jam.h"

#ifndef USE_MD_STUBS
#include "stubs.h"

extern void *jni_env;

/* Static signatures */

/* Non-static signatures */


JNIStub jni_static_stubs[] = {
    {NULL, NULL}
};

JNIStub jni_stubs[] = {
    {NULL, NULL}
};
#endif
